-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- [[ Script name: OfflineEarningsRoot, time of decompilation: Sun May  3 10:12:13 2026 ]]
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local OfflineEarningsBurstLayer = require(ReplicatedStorage.Source.Features.OfflineEarnings.UI.Components.OfflineEarningsBurstLayer)

return function() -- line: 6
	-- upvalues: OfflineEarningsBurstLayer (copy)
	return { OfflineEarningsBurstLayer() }
end
