-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- [[ Script name: UpgradeSlice, time of decompilation: Sun May  3 10:11:34 2026 ]]
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Vide = require(ReplicatedStorage.Packages.Vide)
local v3 = Vide.source(false)
local v4 = Vide.source("main")
local v5 = Vide.source(0)
local v6 = Vide.source(false)

return {
	shown = v3,
	tree = v4,
	inputEndedTime = v5,
	moving = v6
}
