-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- [[ Script name: MonetizationSlice, time of decompilation: Sun May  3 10:12:04 2026 ]]
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Vide = require(ReplicatedStorage.Packages.Vide)

require(ReplicatedStorage.Source.Features.Monetization.MonetizationServiceUtils)

local v3 = Vide.source(nil)
local v4 = Vide.source(nil)

return {
	giftingProduct = v3,
	giftReceivedData = v4
}
