-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- [[ Script name: UIGradient, time of decompilation: Sun May  3 10:11:03 2026 ]]
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Vide = require(ReplicatedStorage.Packages.Vide)

require(ReplicatedStorage.Source.Core.UI.UITypes)

return function(t1: {[any]: any}) -- line: 17
	-- upvalues: Vide (copy)
	return Vide.create("UIGradient")(t1)
end
