-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- [[ Script name: UIListLayout, time of decompilation: Sun May  3 10:11:02 2026 ]]
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Vide = require(ReplicatedStorage.Packages.Vide)

require(ReplicatedStorage.Source.Core.UI.UITypes)

return function(t1: {[any]: any}) -- line: 21
	-- upvalues: Vide (copy)
	return Vide.create("UIListLayout")(t1)
end
