-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- [[ Script name: CodeServiceUtils, time of decompilation: Sun May  3 10:12:11 2026 ]]
return {
	REDEEM_ENUMS = {
		invalid = 0,
		expired = 1,
		outOfUses = 2,
		alreadyRedeemed = 3,
		err = 4,
		success = 5,
		wrongUser = 6
	},
	ERROR_CODES = {
		[0] = "Invalid!",
		[1] = "Expired!",
		[2] = "Out of uses!",
		[3] = "Already redeemed!",
		[4] = "Error!",
		[5] = "Success!",
		[6] = "Invalid UserId!"
	}
}
